import { useEffect, useMemo, useState } from "react";
import { api } from "./client";
import { Image, runLabel } from "./components";
import { parseProtocolVisibility, protocolDefinitions, protocolVisibilityStorageKey, selectedVisibleProtocol, setProtocolVisibility, visibleProtocolIds, type ProtocolId, type ProtocolVisibility } from "./protocols";
import type { Analysis, Cohort, Job, Model, Query, Run } from "./types";

const labels = ["preservation_failure","under_edit","over_edit","partial_edit","wrong_attribute","wrong_entity_binding","reference_dominance","text_dominance","fine_grained_visual_confusion","ambiguous_ground_truth","possible_dataset_issue","duplicate_or_near_duplicate","other","unknown"];
const pages = ["Dashboard","Models","Evaluation Runs","Sample Explorer","Compare Models","Common Failures","Disagreement","Failure Analytics","Annotations","Hypotheses"];

export default function App() {
 const [page,setPage]=useState("Dashboard"),[models,setModels]=useState<Model[]>([]),[runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState<string[]>([]),[protocol,setProtocol]=useState<ProtocolId>("fashioniq_original_split"),[visibility,setVisibility]=useState<ProtocolVisibility>(()=>parseProtocolVisibility(localStorage.getItem(protocolVisibilityStorageKey))),[queries,setQueries]=useState<Query[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[query,setQuery]=useState<Query|null>(null),[k,setK]=useState(10),[analysis,setAnalysis]=useState<Analysis[]>([]),[jaccard,setJaccard]=useState<{left_run_id:string;right_run_id:string;jaccard:number}[]>([]),[error,setError]=useState(""),[annotations,setAnnotations]=useState<string[]>([]),[note,setNote]=useState(""),[cohorts,setCohorts]=useState<Cohort[]>([]),[jobs,setJobs]=useState<Job[]>([]),[cohortName,setCohortName]=useState(""),[failurePreset,setFailurePreset]=useState("all"),[category,setCategory]=useState(""),[failure,setFailure]=useState(""),[minRank,setMinRank]=useState(""),[maxRank,setMaxRank]=useState(""),[order,setOrder]=useState("worst"),[jump,setJump]=useState("");
 const visibleProtocols=useMemo(()=>visibleProtocolIds(visibility),[visibility]);
 const setProtocolVisible=(id:ProtocolId,visible:boolean)=>setVisibility(old=>setProtocolVisibility(old,id,visible));
 const compatible=useMemo(()=>Array.isArray(runs)?runs.filter(run=>run.protocol_id===protocol):[],[runs,protocol]); const selectedRuns=useMemo(()=>Array.isArray(runs)?runs.filter(run=>(selected||[]).includes(run.run_id)):[],[runs,selected]); const mockRuns=(runs||[]).filter(run=>run.data_kind==="mock"), experiments=(runs||[]).filter(run=>run.data_kind==="experiment");
 const refresh=()=>Promise.all([api<Model[]>("/api/models"),api<Run[]>("/api/runs"),api<Cohort[]>("/api/cohorts"),api<Job[]>("/api/jobs")]).then(([m,r,c,j])=>{const safeModels=Array.isArray(m)?m:[], safeRuns=Array.isArray(r)?r:[], safeCohorts=Array.isArray(c)?c:[], safeJobs=Array.isArray(j)?j:[];setModels(safeModels);setRuns(safeRuns);setCohorts(safeCohorts);setJobs(safeJobs);setSelected(old=>{const prior=old||[];return prior.length?prior:safeRuns.filter(x=>x.protocol_id===protocol).map(x=>x.run_id);});}).catch(e=>setError(e.message));
 useEffect(()=>{refresh();},[]); useEffect(()=>{localStorage.setItem(protocolVisibilityStorageKey,JSON.stringify(visibility));},[visibility]); useEffect(()=>{const visible=selectedVisibleProtocol(protocol,visibility);if(visible!==protocol){setProtocol(visible);resetFilters();}},[protocol,visibility,visibleProtocols]); useEffect(()=>{const timer=window.setInterval(()=>api<Job[]>("/api/jobs").then(setJobs).catch(e=>setError(e.message)),2000);return()=>window.clearInterval(timer);},[]); useEffect(()=>{const ids=compatible.map(x=>x.run_id);setSelected(old=>{const retained=(old||[]).filter(id=>ids.includes(id));return retained.length?retained:ids;});},[protocol,runs]);
 const loadPage=()=>{const runId=selected[0];if(!runId)return;const p=new URLSearchParams({run_id:runId,limit:"20",offset:String(offset),order});if(category)p.set("category",category);if(failure)p.set("failed_at",failure);if(minRank)p.set("min_rank",minRank);if(maxRank)p.set("max_rank",maxRank);api<{items:Query[];total:number}>(`/api/queries?${p}`).then(data=>{setQueries(data.items);setTotal(data.total);setQuery(current=>data.items.find(x=>x.query_id===current?.query_id)||data.items[0]||null);}).catch(e=>setError(e.message));};
 useEffect(loadPage,[selected,offset,category,failure,minRank,maxRank,order]); useEffect(()=>{if(selected.length<2){setAnalysis([]);setJaccard([]);return;}const ids=selected.join(",");Promise.all([api<Analysis[]>(`/api/analysis?run_ids=${ids}&k=${k}`),api<{left_run_id:string;right_run_id:string;jaccard:number}[]>(`/api/analysis/failure-jaccard?run_ids=${ids}&k=${k}`)]).then(([a,j])=>{setAnalysis(a);setJaccard(j);}).catch(e=>setError(e.message));},[selected,k]); useEffect(()=>{if(query)api<{labels:string[];note:string}[]>(`/api/annotations?query_id=${encodeURIComponent(query.query_id)}&protocol_id=${protocol}`).then(x=>{setAnnotations(x[0]?.labels||[]);setNote(x[0]?.note||"");}).catch(e=>setError(e.message));},[query,protocol]);
 const resetFilters=()=>setOffset(0); const toggle=(id:string)=>setSelected(old=>(old||[]).includes(id)?(old||[]).filter(x=>x!==id):[...(old||[]),id]); const openQuery=(id:string)=>{const runId=selected[0];if(!runId)return;api<{items:Query[]}>(`/api/queries?run_id=${encodeURIComponent(runId)}&query_id=${encodeURIComponent(id)}&limit=1`).then(x=>{if(!x.items[0])throw Error("query not found");setQuery(x.items[0]);setPage("Sample Explorer");}).catch(e=>setError(e.message));};
 const shown=analysis.filter(row=>!category||row.category===category).filter(row=>failurePreset==="all"||failurePreset==="allfail"&&row.consensus_fail_fraction===1||failurePreset==="80"&&row.consensus_fail_fraction>=.8||failurePreset==="50"&&row.consensus_fail_fraction>=.5||failurePreset==="winner"&&row.min_rank<=k&&row.max_rank>k||failurePreset==="easy"&&row.max_rank<=k).sort((a,b)=>page==="Disagreement"?b.rank_range-a.rank_range:b.consensus_fail_fraction-a.consensus_fail_fraction);
 const saveAnnotation=()=>query&&api("/api/annotations",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({query_id:query.query_id,protocol_id:protocol,labels:annotations,note})}).catch(e=>setError(e.message)); const saveCohort=()=>shown.length&&api("/api/cohorts",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({cohort_id:cohortName||`cohort-${Date.now()}`,protocol_id:protocol,query_ids:shown.map(x=>x.query_id),run_ids:selected,definition:{failurePreset,k,category},notes:""})}).then(refresh).catch(e=>setError(e.message)); const queue=(model:Model,checkpoint:string)=>api<Job>("/api/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model_id:model.model_id,checkpoint_id:checkpoint,protocol_id:model.native_protocol,top_k:200})}).then(job=>setJobs(old=>[...old,job])).catch(e=>setError(e.message));
 const mockBanner=!experiments.length?"MOCK DEVELOPMENT DATA — no real evaluation results are loaded":mockRuns.length?"Mock and real experiment runs are loaded. Mock results are excluded from research conclusions.":"";
 return <main><header><div><h1>CIR Failure Analysis Workbench</h1><p>Canonical JSON source; DuckDB serving index.</p></div>{mockBanner&&<strong className="mock-banner">{mockBanner}</strong>}</header>{error&&<aside className="error"><b>Guard/API error:</b> {error}<button onClick={()=>setError("")}>Dismiss</button></aside>}<nav>{pages.map(x=><button key={x} className={page===x?"active":""} onClick={()=>setPage(x)}>{x}</button>)}</nav><section className="controls"><label>Protocol <select value={protocol} onChange={e=>{setProtocol(e.target.value as ProtocolId);resetFilters();}}>{protocolDefinitions.filter(({id})=>visibility[id]).map(({id,label})=><option key={id} value={id}>{label}</option>)}</select></label><fieldset className="protocol-visibility"><legend>Protocol visibility</legend>{protocolDefinitions.map(({id,label})=><label key={id}><input type="checkbox" checked={visibility[id]} onChange={e=>setProtocolVisible(id,e.target.checked)}/>{label}</label>)}</fieldset><label>Top-K <select value={k} onChange={e=>setK(+e.target.value)}>{[1,5,10,20,50,100,200].map(x=><option key={x}>{x}</option>)}</select></label><span>{selected.length} compatible runs selected</span></section>
 {page==="Dashboard"&&<section><h2>Dashboard</h2><div className="cards"><b>{models.length} registered models</b><b>{experiments.length} experiment runs</b><b>{mockRuns.length} mock runs</b></div><p>Paper scores are sanity references only. Cross-protocol analysis fails closed.</p></section>}
 {page==="Models"&&<section><h2>Models</h2><table><tbody>{models.map(m=><tr key={m.model_id}><td><b>{m.method_name}</b><br/>{m.reproduction_status}<br/><small>{m.native_protocol||"protocol unavailable"} · literature {m.literature_split_label}</small></td><td>{m.checkpoints.map(c=><div className="checkpoint" key={c.checkpoint_id}>{c.checkpoint_id}: {c.checkpoint_downloaded?"installed":"not installed"}<br/><small>auto {String(c.automatic_download_available)} · mapping {String(c.mapping_verified)} · command {String(c.adapter_command_ready)} · runtime {String(c.runtime_verified)}</small><br/><button disabled={!c.runnable||!m.native_protocol} onClick={()=>queue(m,c.checkpoint_id)}>Queue official evaluation</button></div>)}</td></tr>)}</tbody></table></section>}
 {page==="Evaluation Runs"&&<section><h2>Evaluation Runs</h2>{compatible.map(run=><label className="run" key={run.run_id}><input type="checkbox" checked={selected.includes(run.run_id)} onChange={()=>toggle(run.run_id)}/><b>{runLabel(run)}</b> <span className="badge">{run.data_kind.toUpperCase()}</span></label>)}<h3>GPU job queue</h3><p>Only preflighted official commands enter queue. One evaluator runs at once.</p>{jobs.length?jobs.map(job=><article className="job" key={job.job_id}><b>{job.model_id} / {job.checkpoint_id}</b> · {job.status}{job.return_code!==null&&` · exit ${job.return_code}`}<br/><small>{job.command.join(" ")}</small>{["queued","running"].includes(job.status)&&<button onClick={()=>api(`/api/jobs/${job.job_id}/cancel`,{method:"POST"}).then(refresh).catch(e=>setError(e.message))}>Cancel</button>}{job.error&&<pre>{job.error}</pre>}{job.stderr_tail&&<pre>{job.stderr_tail}</pre>}</article>):<p>No evaluation jobs.</p>}</section>}
 {page==="Sample Explorer"&&<section><h2>Sample Explorer</h2><div className="filters"><label>Category <select value={category} onChange={e=>{setCategory(e.target.value);resetFilters();}}><option value="">All</option>{["dress","shirt","toptee"].map(x=><option key={x}>{x}</option>)}</select></label><label>Failure <select value={failure} onChange={e=>{setFailure(e.target.value);resetFilters();}}><option value="">All</option><option value="10">fail @10</option><option value="50">fail @50</option></select></label><input placeholder="min rank" value={minRank} onChange={e=>{setMinRank(e.target.value);resetFilters();}}/><input placeholder="max rank" value={maxRank} onChange={e=>{setMaxRank(e.target.value);resetFilters();}}/><select value={order} onChange={e=>{setOrder(e.target.value);resetFilters();}}><option value="worst">worst first</option><option value="best">best first</option></select><input placeholder="Paste query ID" value={jump} onChange={e=>setJump(e.target.value)}/><button onClick={()=>openQuery(jump)}>Jump</button></div><div className="pager"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-20))}>Previous page</button><span>{offset+1}–{Math.min(offset+20,total)} of {total}</span><button disabled={offset+20>=total} onClick={()=>setOffset(offset+20)}>Next page</button></div>{query&&<><h3>{query.query_id} · target rank {query.target_rank}</h3><div className="images"><Image category={query.category} id={query.reference_id} kind="Reference"/><Image category={query.category} id={query.target_id} kind="Target"/></div><p>{query.raw_captions.join(" / ")}<br/><code>{query.model_input_text}</code></p><div className="grid">{query.top_results.slice(0,k).map(x=><article className={x.image_id===query.target_id?"target":""} key={x.rank}><Image category={query.category} id={x.image_id} kind={`#${x.rank}`}/><small>{x.score.toFixed(4)}</small></article>)}</div></>}</section>}
 {page==="Compare Models"&&<section><h2>Compare Models</h2>{query&&<Compare query={query} runIds={selected} k={k} onError={setError}/>}</section>}
 {["Common Failures","Disagreement"].includes(page)&&<section><h2>{page}</h2><div className="filters"><select value={failurePreset} onChange={e=>setFailurePreset(e.target.value)}><option value="all">All</option><option value="allfail">All runs fail</option><option value="80">≥80% fail</option><option value="50">≥50% fail</option><option value="winner">One run succeeds</option><option value="easy">Universal success</option></select><button onClick={saveCohort}>Save filtered set</button><input placeholder="cohort ID" value={cohortName} onChange={e=>setCohortName(e.target.value)}/></div><AnalysisTable rows={shown} onOpen={openQuery}/></section>}
 {page==="Failure Analytics"&&<section><h2>Failure Analytics</h2><AnalysisTable rows={shown} onOpen={openQuery}/><h3>Failure-set Jaccard</h3><table><thead><tr><th>run</th>{selectedRuns.map(r=><th key={r.run_id}>{runLabel(r)}</th>)}</tr></thead><tbody>{selectedRuns.map(left=><tr key={left.run_id}><th>{runLabel(left)}</th>{selectedRuns.map(right=><td key={right.run_id}>{jaccard.find(x=>x.left_run_id===left.run_id&&x.right_run_id===right.run_id)?.jaccard.toFixed(2)||"—"}</td>)}</tr>)}</tbody></table><h3>Query × run target rank</h3><table><thead><tr><th>query</th>{selectedRuns.map(r=><th key={r.run_id}>{runLabel(r)}</th>)}</tr></thead><tbody>{shown.map(row=><tr key={row.query_id} onClick={()=>openQuery(row.query_id)}><td>{row.query_id}</td>{selectedRuns.map(r=><td key={r.run_id}>{row.target_rank[r.run_id]}</td>)}</tr>)}</tbody></table></section>}
 {page==="Annotations"&&<section><h2>Annotations</h2>{query&&<><p>{query.query_id} · {protocol}</p><div className="labels">{labels.map(x=><label key={x}><input type="checkbox" checked={annotations.includes(x)} onChange={()=>setAnnotations(old=>old.includes(x)?old.filter(y=>y!==x):[...old,x])}/>{x}</label>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)}/><button onClick={saveAnnotation}>Save / update</button></>}</section>}
 {page==="Hypotheses"&&<section><h2>Hypotheses</h2>{cohorts.map(c=><article key={c.cohort_id}><b>{c.cohort_id}</b> · {c.query_ids.length} queries · {c.run_ids.length} runs</article>)}</section>}</main>;
}
function AnalysisTable({rows,onOpen}:{rows:Analysis[];onOpen:(id:string)=>void}) {return <table><thead><tr><th>Query</th><th>Fail</th><th>Median</th><th>Range</th><th>Common distractor</th></tr></thead><tbody>{rows.map(r=><tr key={r.query_id} onClick={()=>onOpen(r.query_id)}><td>{r.query_id}</td><td>{(r.consensus_fail_fraction*100).toFixed(0)}%</td><td>{r.median_rank}</td><td>{r.rank_range}</td><td>{r.common_distractors[0]&&`${r.common_distractors[0].image_id} (${r.common_distractors[0].run_count} runs)`}</td></tr>)}</tbody></table>}
function Compare({query,runIds,k,onError}:{query:Query;runIds:string[];k:number;onError:(x:string)=>void}) {const [rows,setRows]=useState<{run:Run;query:Query}[]>([]);useEffect(()=>{if(runIds.length>1)api<{run:Run;query:Query}[]>(`/api/compare/${encodeURIComponent(query.query_id)}?run_ids=${runIds.join(",")}&k=${k}`).then(setRows).catch(e=>onError(e.message));},[query.query_id,runIds.join(","),k]);const counts=new Map<string,number>();rows.forEach(r=>r.query.top_results.slice(0,k).forEach(x=>counts.set(x.image_id,(counts.get(x.image_id)||0)+1)));return <>{<div className="images"><Image category={query.category} id={query.reference_id} kind="Reference"/><Image category={query.category} id={query.target_id} kind="Ground-truth target"/></div>}<p>{query.raw_captions.join(" / ")}</p>{rows.map(row=><article key={row.run.run_id}><b>{runLabel(row.run)}</b> · target rank {row.query.target_rank}<div className="grid">{row.query.top_results.slice(0,k).map(x=><article className={x.image_id===row.query.target_id?"target":""} key={x.rank}><Image category={row.query.category} id={x.image_id} kind={`#${x.rank}`}/><small>{x.score.toFixed(4)} {x.image_id!==row.query.target_id&&(counts.get(x.image_id)||0)>1&&<span className="shared">shared by {counts.get(x.image_id)}/{rows.length} runs</span>}</small></article>)}</div></article>)}</>}
