import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type TopResult = { rank:number; image_id:string; score:number };
type Query = { query_id:string; category:string; reference_id:string; target_id:string; raw_captions:string[]; model_input_text:string; target_rank:number; top_results:TopResult[] };
type Run = { run_id:string; protocol_id:string; model_id:string; method_name:string; checkpoint_id:string; checkpoint_training_noise_pct:number|null; data_kind:"mock"|"experiment"; top_k_saved:number };
type Model = { model_id:string; method_name:string; native_protocol:string|null; reproduction_status:string; strict_clean_checkpoint_available:boolean|null; checkpoints:{checkpoint_id:string; automatic_download_available:boolean; checkpoint_downloaded:boolean; local_sha256:string|null; official_sha256_known:boolean; mapping_verified:boolean; adapter_command_ready:boolean; runtime_verified:boolean; runnable:boolean; blocking_reasons:string[]}[] };
type Analysis = { query_id:string; category:string; target_rank:Record<string,number>; consensus_fail_fraction:number; min_rank:number; max_rank:number; median_rank:number; rank_range:number; rank_std:number; mean_topk_jaccard:number; common_distractors:{image_id:string;run_count:number;best_rank:number;mean_rank:number}[] };
type Cohort = { cohort_id:string; protocol_id:string; query_ids:string[]; run_ids:string[]; definition:Record<string,unknown>; notes:string; created_at:string };
const BASE = "http://127.0.0.1:8000";
const labels = ["preservation_failure","under_edit","over_edit","partial_edit","wrong_attribute","wrong_entity_binding","reference_dominance","text_dominance","fine_grained_visual_confusion","ambiguous_ground_truth","possible_dataset_issue","duplicate_or_near_duplicate","other","unknown"];
async function api<T>(path:string, init?:RequestInit):Promise<T> { const response=await fetch(`${BASE}${path}`,init); const payload=await response.json().catch(()=>null); if(!response.ok) throw new Error(payload?.message || payload?.detail?.message || JSON.stringify(payload) || response.statusText); return payload; }
function Image({category,id,kind}:{category:string;id:string;kind:string}) { return <figure><img src={`${BASE}/api/images/${category}/${encodeURIComponent(id)}`} alt={`${kind}: ${id}`} onError={event=>{event.currentTarget.style.display="none"}}/><figcaption>{kind}: {id}</figcaption></figure>; }
function App() {
 const [page,setPage]=useState("Dashboard"), [models,setModels]=useState<Model[]>([]), [runs,setRuns]=useState<Run[]>([]), [selected,setSelected]=useState<string[]>([]), [protocol,setProtocol]=useState("fashioniq_original_split"), [queries,setQueries]=useState<Query[]>([]), [total,setTotal]=useState(0), [offset,setOffset]=useState(0), [query,setQuery]=useState<Query|null>(null), [k,setK]=useState(10), [analysis,setAnalysis]=useState<Analysis[]>([]), [jaccard,setJaccard]=useState<unknown[]>([]), [error,setError]=useState(""), [annotations,setAnnotations]=useState<string[]>([]), [note,setNote]=useState(""), [cohorts,setCohorts]=useState<Cohort[]>([]), [cohortName,setCohortName]=useState(""), [filter,setFilter]=useState("all");
 const compatible=useMemo(()=>runs.filter(run=>run.protocol_id===protocol),[runs,protocol]);
 const selectedRuns=useMemo(()=>runs.filter(run=>selected.includes(run.run_id)),[runs,selected]);
 const mockRuns=runs.filter(run=>run.data_kind==="mock"); const experimentRuns=runs.filter(run=>run.data_kind==="experiment");
 const refresh=()=>Promise.all([api<Model[]>("/api/models"),api<Run[]>("/api/runs"),api<Cohort[]>("/api/cohorts")]).then(([m,r,c])=>{setModels(m);setRuns(r);setCohorts(c); const original=r.filter(run=>run.protocol_id==="fashioniq_original_split").map(run=>run.run_id); setSelected(old=>old.length?old:original);}).catch(error=>setError(error.message));
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{const ids=compatible.map(run=>run.run_id); setSelected(old=>old.filter(id=>ids.includes(id)).length?old.filter(id=>ids.includes(id)):ids);},[protocol,runs]);
 useEffect(()=>{const runId=selected[0]; if(!runId)return; api<{items:Query[];total:number}>(`/api/queries?run_id=${encodeURIComponent(runId)}&limit=20&offset=${offset}&order=worst`).then(data=>{setQueries(data.items);setTotal(data.total);setQuery(current=>data.items.find(item=>item.query_id===current?.query_id)||data.items[0]||null)}).catch(error=>setError(error.message));},[selected,offset]);
 useEffect(()=>{if(selected.length<2){setAnalysis([]);setJaccard([]);return} const ids=selected.join(","); Promise.all([api<Analysis[]>(`/api/analysis?run_ids=${ids}&k=${k}`),api<unknown[]>(`/api/analysis/failure-jaccard?run_ids=${ids}&k=${k}`)]).then(([rows,matrix])=>{setAnalysis(rows);setJaccard(matrix)}).catch(error=>setError(error.message));},[selected,k]);
 useEffect(()=>{if(!query)return; api<{labels:string[];note:string}[]>(`/api/annotations?query_id=${encodeURIComponent(query.query_id)}&protocol_id=${protocol}`).then(rows=>{setAnnotations(rows[0]?.labels||[]);setNote(rows[0]?.note||"")}).catch(error=>setError(error.message));},[query,protocol]);
 const toggle=(id:string)=>setSelected(old=>old.includes(id)?old.filter(item=>item!==id):[...old,id]);
 const openQuery=(row:Analysis)=>{const runId=selected[0]; if(!runId)return; api<{items:Query[]}>(`/api/queries?run_id=${encodeURIComponent(runId)}&query_id=${encodeURIComponent(row.query_id)}&limit=1`).then(data=>{setQuery(data.items[0]||null);setPage("Sample Explorer")}).catch(error=>setError(error.message));};
 const saveAnnotation=async()=>{if(!query)return; try{await api("/api/annotations",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({query_id:query.query_id,protocol_id:protocol,labels:annotations,note})});setError("")}catch(error){setError((error as Error).message)}};
 const saveCohort=async(rows:Analysis[]=analysis)=>{const queryIds=rows.map(row=>row.query_id); if(!queryIds.length)return; try{await api("/api/cohorts",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({cohort_id:cohortName||`cohort-${Date.now()}`,protocol_id:protocol,query_ids:queryIds,run_ids:selected,definition:{filter,k},notes:"Mock development cohort; not research evidence."})});setCohortName("");refresh()}catch(error){setError((error as Error).message)}};
 const shown=analysis.filter(row=>filter==="all"||filter==="fail"&&row.consensus_fail_fraction===1||filter==="winner"&&row.min_rank<=k&&row.max_rank>k||filter==="easy"&&row.max_rank<=k).sort((left,right)=>page==="Disagreement"?right.rank_range-left.rank_range:right.consensus_fail_fraction-left.consensus_fail_fraction);
 const currentIndex=queries.findIndex(item=>item.query_id===query?.query_id);
 return <main><header><div><h1>CIR Failure Analysis Workbench</h1><p>Local research UI. Canonical JSON remains source of truth; DuckDB is derived.</p></div><strong className="mock-banner">MOCK DEVELOPMENT DATA — no real evaluation results are loaded</strong></header>{error&&<aside className="error"><b>Guard/API error:</b> {error}<button onClick={()=>setError("")}>Dismiss</button></aside>}
 <nav>{["Dashboard","Models","Evaluation Runs","Sample Explorer","Compare Models","Common Failures","Disagreement","Failure Analytics","Annotations","Hypotheses"].map(item=><button key={item} className={page===item?"active":""} onClick={()=>setPage(item)}>{item}</button>)}</nav>
 <section className="controls"><label>Protocol <select value={protocol} onChange={event=>{setProtocol(event.target.value);setOffset(0)}}><option value="fashioniq_original_split">FashionIQ — Original Split</option><option value="fashioniq_val_split">FashionIQ — Val Split</option></select></label><label>Top-K <select value={k} onChange={event=>setK(+event.target.value)}>{[1,5,10,20,50,100,200].map(value=><option key={value}>{value}</option>)}</select></label><span>{selected.length} compatible runs selected</span></section>
 {page==="Dashboard"&&<section><h2>Dashboard</h2><div className="cards"><b>{models.length} registered models</b><b>{experimentRuns.length} experiment runs</b><b>{mockRuns.length} mock runs</b><b>{new Set(runs.map(run=>run.protocol_id)).size} protocols</b></div><p>Paper scores are sanity references only. Cross-protocol analytics, cohorts, and consensus fail closed.</p></section>}
 {page==="Models"&&<section><h2>Models</h2><table><thead><tr><th>Method</th><th>Protocol</th><th>Checkpoint readiness</th></tr></thead><tbody>{models.map(model=><tr key={model.model_id}><td><b>{model.method_name}</b><br/><small>{model.reproduction_status}</small></td><td>{model.native_protocol||"BLOCKED"}</td><td>{model.checkpoints.length?model.checkpoints.map(checkpoint=><div className="checkpoint" key={checkpoint.checkpoint_id}><b>{checkpoint.checkpoint_id}</b> {checkpoint.checkpoint_downloaded?"installed":"not installed"}<br/><small>source metadata {String(checkpoint.mapping_verified)} · auto download {String(checkpoint.automatic_download_available)} · local SHA {checkpoint.local_sha256||"not computed"} · official SHA {checkpoint.official_sha256_known?"known":"not published"} · command ready {String(checkpoint.adapter_command_ready)} · runtime verified {String(checkpoint.runtime_verified)}</small><br/><code>python workbench/scripts/download_checkpoints.py --model {model.model_id} --checkpoint {checkpoint.checkpoint_id}</code></div>):"NO VERIFIED FASHIONIQ CHECKPOINT"}</td></tr>)}</tbody></table></section>}
 {page==="Evaluation Runs"&&<section><h2>Evaluation Runs</h2>{compatible.map(run=><label className="run" key={run.run_id}><input type="checkbox" checked={selected.includes(run.run_id)} onChange={()=>toggle(run.run_id)}/><b>{run.method_name}</b> / {run.checkpoint_id} / <span className="badge">{run.data_kind.toUpperCase()}</span>{run.checkpoint_training_noise_pct!==null&&<> / trained with {run.checkpoint_training_noise_pct}% noise; evaluated at 0%</>}</label>)}</section>}
 {page==="Sample Explorer"&&<section><h2>Sample Explorer</h2><div className="pager"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>Previous page</button><span>{offset+1}–{Math.min(offset+20,total)} of {total}</span><button disabled={offset+20>=total} onClick={()=>setOffset(offset+20)}>Next page</button></div>{query&&<><div className="pager"><button disabled={currentIndex<=0} onClick={()=>setQuery(queries[currentIndex-1])}>Previous</button><button disabled={!queries.length} onClick={()=>setQuery(queries[Math.floor(Math.random()*queries.length)])}>Random</button><button disabled={currentIndex===queries.length-1} onClick={()=>setQuery(queries[currentIndex+1])}>Next</button></div><h3>{query.query_id} · target rank {query.target_rank}</h3><div className="images"><Image category={query.category} id={query.reference_id} kind="Reference"/><Image category={query.category} id={query.target_id} kind="Target"/></div><p>{query.raw_captions.join(" / ")}<br/><code>{query.model_input_text}</code></p><div className="grid">{query.top_results.slice(0,k).map(result=><article className={result.image_id===query.target_id?"target":""} key={result.rank}><Image category={query.category} id={result.image_id} kind={`#${result.rank}`}/><small>{result.score.toFixed(4)}</small></article>)}</div></>}</section>}
 {page==="Compare Models"&&<section><h2>Compare Models</h2>{query&&<><h3>{query.query_id}</h3><div className="images"><Image category={query.category} id={query.reference_id} kind="Reference"/><Image category={query.category} id={query.target_id} kind="Target"/></div>{selected.length<2?<p>Select at least two same-protocol runs.</p>:<Compare queryId={query.query_id} runIds={selected} k={k} onError={setError}/>}</>}</section>}
 {["Common Failures","Disagreement","Failure Analytics"].includes(page)&&<section><h2>{page}</h2><div className="filters"><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All selected queries</option><option value="fail">All runs fail at K</option><option value="winner">One run solves</option><option value="easy">Universal success</option></select><button onClick={()=>saveCohort(shown)}>Save filtered set as cohort</button><input value={cohortName} onChange={event=>setCohortName(event.target.value)} placeholder="optional cohort ID"/></div><table><thead><tr><th>Query</th><th>Fail @K</th><th>Median</th><th>Range</th><th>Jaccard</th><th>Common distractor</th></tr></thead><tbody>{shown.map(row=><tr key={row.query_id} onClick={()=>openQuery(row)}><td>{row.query_id}</td><td>{(100*row.consensus_fail_fraction).toFixed(0)}%</td><td>{row.median_rank}</td><td>{row.rank_range}</td><td>{row.mean_topk_jaccard.toFixed(2)}</td><td>{row.common_distractors[0]?.image_id||"—"} ({row.common_distractors[0]?.run_count||0} runs)</td></tr>)}</tbody></table>{page==="Failure Analytics"&&<pre>{JSON.stringify(jaccard,null,2)}</pre>}</section>}
 {page==="Annotations"&&<section><h2>Annotations</h2>{query?<><p>{query.query_id} · {protocol}. Dataset-query scoped; raw result JSON never changes.</p><div className="labels">{labels.map(label=><label key={label}><input type="checkbox" checked={annotations.includes(label)} onChange={()=>setAnnotations(old=>old.includes(label)?old.filter(item=>item!==label):[...old,label])}/>{label}</label>)}</div><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Evidence note"/><div><button onClick={saveAnnotation}>Save / update</button><button onClick={()=>{setAnnotations([]);setNote("")}}>Clear</button></div></>:<p>Select a query in Sample Explorer.</p>}</section>}
 {page==="Hypotheses"&&<section><h2>Hypotheses / saved cohorts</h2><p>Saved cohorts preserve protocol, run IDs, filters, query IDs, and notes. Mock cohorts are development fixtures, not findings.</p>{cohorts.map(cohort=><article key={cohort.cohort_id}><b>{cohort.cohort_id}</b> · {cohort.protocol_id} · {cohort.query_ids.length} queries · {cohort.run_ids.length} runs<br/><small>{cohort.notes}</small><div>{["json","csv","markdown"].map(format=><button key={format} onClick={()=>api<{content?:string}>(`/api/cohorts/${encodeURIComponent(cohort.cohort_id)}/export/${format}`).then(result=>{const text=result.content||JSON.stringify(result,null,2); const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));link.download=`${cohort.cohort_id}.${format}`;link.click();URL.revokeObjectURL(link.href)}).catch(error=>setError(error.message))}>Export {format}</button>)}</div></article>)}</section>}
 </main>;
}
function Compare({queryId,runIds,k,onError}:{queryId:string;runIds:string[];k:number;onError:(error:string)=>void}) { const [rows,setRows]=useState<{run:Run;query:Query}[]>([]); useEffect(()=>{api<{run:Run;query:Query}[]>(`/api/compare/${encodeURIComponent(queryId)}?run_ids=${runIds.join(",")}`).then(setRows).catch(error=>onError(error.message));},[queryId,runIds.join(",")]); return <div>{rows.map(row=><article key={row.run.run_id}><b>{row.run.method_name} / {row.run.checkpoint_id}</b> — target rank {row.query.target_rank}<div className="grid">{row.query.top_results.slice(0,k).map(item=><span className={item.image_id===row.query.target_id?"target":""} key={item.rank}>#{item.rank} {item.image_id}</span>)}</div></article>)}</div>; }
createRoot(document.getElementById("root")!).render(<App/>);
