import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type Run = {run_id:string; protocol_id:string; model_id:string; method_name:string; data_kind:string};
type Query = {query_id:string; category:string; reference_id:string; target_id:string; raw_captions:string[]; model_input_text:string; target_rank:number; top_results:{rank:number;image_id:string;score:number}[]};
type Model = {model_id:string;method_name:string;native_protocol:string|null;reproduction_status:string;strict_clean_checkpoint_available:boolean|null;checkpoints:{checkpoint_id:string;checkpoint_downloaded:boolean;runnable:boolean;blocking_reasons:string[]}[]};
const api = (path:string) => fetch(`http://127.0.0.1:8000${path}`).then(r => r.ok ? r.json() : r.text().then(x => Promise.reject(x)));
function App() {
 const [page,setPage]=useState("Dashboard"), [models,setModels]=useState<Model[]>([]), [runs,setRuns]=useState<Run[]>([]), [selected,setSelected]=useState<string[]>([]), [queries,setQueries]=useState<Query[]>([]), [query,setQuery]=useState<Query|null>(null), [k,setK]=useState(10), [analysis,setAnalysis]=useState<any[]>([]), [error,setError]=useState("");
 useEffect(()=>{Promise.all([api("/api/models"),api("/api/runs")]).then(([m,r])=>{setModels(m);setRuns(r);setSelected(r.filter((x:Run)=>x.protocol_id==="fashioniq_original_split").map((x:Run)=>x.run_id));}).catch(setError)},[]);
 const protocol=useMemo(()=>runs.find(x=>selected.includes(x.run_id))?.protocol_id,[runs,selected]);
 useEffect(()=>{if(selected[0]) api(`/api/queries?run_id=${selected[0]}`).then((q:Query[])=>{setQueries(q);setQuery(q[0]||null)}).catch(setError)},[selected]);
 useEffect(()=>{if(selected.length>1) api(`/api/analysis?run_ids=${selected.join(",")}&k=${k}`).then(setAnalysis).catch(setError)},[selected,k]);
 const toggle=(id:string)=>setSelected(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
 return <main><header><h1>CIR Failure Analysis Workbench</h1><small>Local mock-data mode. No checkpoint downloads or inference.</small></header><nav>{["Dashboard","Models","Evaluation Runs","Sample Explorer","Compare Models","Common Failures","Disagreement","Failure Analytics","Annotations","Hypotheses"].map(x=><button className={page===x?"active":""} onClick={()=>setPage(x)}>{x}</button>)}</nav>{error&&<p className="error">{error}</p>}
 <section className="controls"><label>Protocol <select value={protocol||""} onChange={e=>setSelected(runs.filter(x=>x.protocol_id===e.target.value).map(x=>x.run_id))}><option value="fashioniq_original_split">FashionIQ — Original Split</option><option value="fashioniq_val_split">FashionIQ — Val Split</option></select></label><label>K <select value={k} onChange={e=>setK(+e.target.value)}>{[1,5,10,20,50,100].map(x=><option>{x}</option>)}</select></label></section>
 {page==="Dashboard"&&<section><h2>Dashboard</h2><div className="cards"><b>{models.length} registered models</b><b>{runs.length} loaded runs</b><b>{runs.filter(x=>x.data_kind==="mock").length} mock runs</b><b>{new Set(runs.map(x=>x.protocol_id)).size} protocols</b></div><p>Paper scores are not locally reproduced scores. Cross-protocol aggregates are blocked.</p></section>}
 {page==="Models"&&<section><h2>Models</h2><table><thead><tr><th>Method</th><th>Protocol</th><th>Checkpoint</th><th>Run</th></tr></thead><tbody>{models.map(m=><tr><td>{m.method_name}<br/><small>{m.reproduction_status}</small></td><td>{m.native_protocol||"BLOCKED"}</td><td>{m.checkpoints.length?m.checkpoints.map(c=><div>{c.checkpoint_id}: {c.checkpoint_downloaded?"DOWNLOADED":"CHECKPOINT NOT DOWNLOADED"}<br/><code>python workbench/scripts/download_checkpoints.py --model {m.model_id}{m.checkpoints.length>1?` --checkpoint ${c.checkpoint_id}`:""}</code></div>):"NO FASHIONIQ CHECKPOINT"}</td><td><button disabled>Run evaluation</button></td></tr>)}</tbody></table></section>}
 {page==="Evaluation Runs"&&<section><h2>Evaluation Runs</h2>{runs.filter(x=>x.protocol_id===protocol).map(r=><label className="run"><input type="checkbox" checked={selected.includes(r.run_id)} onChange={()=>toggle(r.run_id)}/>{r.method_name} — {r.run_id} <em>{r.data_kind}</em></label>)}</section>}
 {page==="Sample Explorer"&&<section><h2>Sample Explorer</h2>{query&&<><button onClick={()=>setQuery(queries[Math.max(0,queries.indexOf(query)-1)])}>Previous</button><button onClick={()=>setQuery(queries[Math.min(queries.length-1,queries.indexOf(query)+1)])}>Next</button><button onClick={()=>setQuery(queries[Math.floor(Math.random()*queries.length)])}>Random</button><h3>{query.query_id} · target rank {query.target_rank}</h3><p>Reference: {query.reference_id} · Target: {query.target_id}<br/>{query.raw_captions.join(" / ")}<br/><code>{query.model_input_text}</code></p><div className="grid">{query.top_results.slice(0,k).map(x=><article className={x.image_id===query.target_id?"target":""}><b>#{x.rank}</b><br/>{x.image_id}<br/>{x.score.toFixed(3)}</article>)}</div></>}</section>}
 {["Compare Models","Common Failures","Disagreement","Failure Analytics"].includes(page)&&<section><h2>{page}</h2><p>Selected runs: {selected.join(", ")}</p><table><thead><tr><th>Query</th><th>Consensus fail @{k}</th><th>Median rank</th><th>Rank range</th><th>Top-K Jaccard</th><th>Common distractor</th></tr></thead><tbody>{analysis.sort((a,b)=>b.consensus_fail_fraction-a.consensus_fail_fraction).map(x=><tr onClick={()=>setPage("Sample Explorer")}><td>{x.query_id}</td><td>{(x.consensus_fail_fraction*100).toFixed(0)}%</td><td>{x.median_rank}</td><td>{x.rank_range}</td><td>{x.mean_topk_jaccard.toFixed(2)}</td><td>{x.common_distractors[0]?.image_id||"—"}</td></tr>)}</tbody></table></section>}
 {["Annotations","Hypotheses"].includes(page)&&<section><h2>{page}</h2><p>Persistent annotation and cohort API is available. Select a sample then annotate labels or save same-protocol run cohort.</p></section>}</main> }
createRoot(document.getElementById("root")!).render(<App/>);
